- name: "get {{ network_plugin }} manifest"
  get_url:
    url: "{{ network_manifest_url }}"
    dest: "/tmp/{{ network_plugin }}.yml"
  when: config_pod_network == true

- name: Config flannel
  include_tasks: flannel.yml
  when: config_pod_network == true and network_plugin == flannel

- name: Config calico
  include_tasks: calico.yml
  when: config_pod_network == true and network_plugin == calico

- name: "Check {{ network_plugin }} daemonset is working"
  shell: kubectl --kubeconfig={{ kubeadmin_config }} get ds --all-namespaces | grep {{ network_plugin }}
  register: check_net
  ignore_errors: true
  changed_when: false

# - name: install the operator on your cluster
#   when: check_net is failed
#   shell: |
#     kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml
#   ignore_errors: true

- name: "install {{ network_plugin }}"
  when: check_net is failed and config_pod_network == true
  shell: |
    kubectl apply -f /tmp/{{ network_plugin }}.yml
  # kubectl apply -f $HOME/manifest/{{ network_plugin }}.yml
  # args:
  #   chdir: $HOME
  ignore_errors: true

- name: "install {{ network_plugin }}"
  when: check_net is failed and config_pod_network == false
  shell: |
    kubectl apply -f {{ network_manifest_url }}
  # kubectl apply -f $HOME/manifest/{{ network_plugin }}.yml
  # args:
  #   chdir: $HOME
  ignore_errors: true

- name: Sleep for 300 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 300