- name: "get {{ network_plugin }} manifest"
  get_url:
    url: "{{ network_manifest_url }}"
    dest: "$HOME/manifest/{{ network_plugin }}.yml"
  become: true

- name: "config ip subnet for {{ network_plugin }}"
  shell: |
    sed -i "/IPV4POOL_CIDR/s/^#//g" $HOME/manifest/{{ network_plugin }}.yml
    sed -i "/192/s/^#//g" $HOME/manifest/{{ network_plugin }}.yml
  when: config_pod_network == true and network_plugin == calico
  become: true

- name: "config ip subnet for {{ network_plugin }}"
  lineinfile:
    path: "$HOME/manifest/{{ network_plugin }}.yml"
    search_string: "10.244.0.0/16"
    line: '"Network": {{ pod_network }}"'
  when: config_pod_network == true and network_plugin == flannel
  become: true

- name: "config ip subnet for {{ network_plugin }}"
  lineinfile:
    path: "$HOME/manifest/{{ network_plugin }}.yml"
    search_string: "192.168.0.0/16"
    line: 'value: "{{ pod_network }}"'
  when: config_pod_network == true and network_plugin == calico
  become: true

- name: "install {{ network_plugin }}"
  # become: yes
  # become_user: ubuntu
  shell: |
    kubectl apply -f $HOME/manifest/{{ network_plugin }}.yml
  # args:
  #   chdir: $HOME
  become: true
