- name: Check if etcd has already run
  stat:
    path: "/etc/etcd/pki/ca.pem"
  register: etcd_ca
  when: etcd_cluster == 'true' and etcd_deployment == 'kubeadm' and not etcd_ca.stat.exists

- name: Gen cert on node 1
  include_tasks: master.yml
  when: etcd_cluster == 'true' and etcd_deployment == 'service' and not etcd_ca.stat.exists

- name: Install etcd
  include_tasks: all.yml
  when: etcd_cluster == 'true' and etcd_deployment == 'service' and not etcd_ca.stat.exists
