- name: gather os specific variables
  # vars:
  #   ansible_os_family: debian
  #   ansible_distribution_release: buster
  include_vars: "../vars/{{ ansible_os_family | lower }}.yml"

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for backend in groups['all'] %}
        {{ hostvars[backend].ansible_all_ipv4_addresses | first }} {{ hostvars[backend]['ansible_hostname'] }}
      {% endfor %}

- name: disable swap
  shell: |
    swapoff -a

- name: disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  become: true

- name: enable kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter
  become: true

- name: configure persistent loading of modules
  copy:
    dest: /etc/modules-load.d/kubernetes.conf
    mode: 0644
    content: "overlay \nbr_netfilter"
  become: true

- name: settings sysctl
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/kubernetes.conf
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  become: true

- import_tasks: "debian.yml"
  when: ansible_os_family == "Debian"
