---
- name: Recreate kube-dns
  command: kubectl --kubeconfig={{ kubeadmin_config }} -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ groups['control-plane'][0] }}"
  ignore_errors: true