- name: configure the kubelet to be a service manager for etcd.
  copy:
    src: 20-etcd-service-manager.conf
    dest: /etc/systemd/system/kubelet.service.d/
  tags:
    # - etcd
    - default

- name: reload systemd
  command: systemctl daemon-reload
  tags:
    # - etcd
    - default

- name: restart kubelet
  service:
    name: kubelet
    state: restarted

- name: create temp directories to store files that will end up on other hosts
  file:
    path: "/tmp/{{ inventory_hostname }}/"
    state: directory
  # loop: "{{ groups['etcd'] }}"

- name: create configuration files for kubeadm
  template:
    src: kubeadmcfg.j2
    dest: "/tmp/{{ inventory_hostname }}/kubeadmcfg.yaml"
    # mode: 0644
    # owner: root
    # group: root
  # notify:
  # loop: "{{ groups['etcd'] }}"
