- name: Generate the certificate authority
  shell: |
    kubeadm init phase certs etcd-ca

- name: fetch certificate authority to local
  fetch:
    src: "/etc/kubernetes/pki/etcd/{{ item }}"
    dest: "{{ folder_path }}"
    flat: yes
  loop:
    - ca.crt
    - ca.key
